FROM rocker/rstudio:devel

RUN apt-get update -qq && apt-get -y --no-install-recommends install \
  libxml2-dev \
  libcairo2-dev \
  libsqlite-dev \
  libmariadbd-dev \
  libmariadbclient-dev \
  libpq-dev \
  libssh2-1-dev \
  && install2.r --error \
    --deps TRUE \
    tidyverse \
    dplyr \
    tidyr \
    caret \
    ggplot2 \
    GGally \
    ISLR \
    glmnet \
    jtools \
    interactions \

ENV PATH="/scripts:${PATH}"