library(ggplot2)
library(tidyverse)
library(dplyr)
library(tidyr)

data <- read.csv('Analysis.csv')
jpeg("rplot.jpg")
a <- ggplot(data, aes(plsEng_TenureYr))
a + geom_bar(aes(fill = plsEng_TenureYr))
dev.off()